### ISSUE TITLE
Issue: tmp.bin removal race condition

### ISSUE THREAD

**Issue by wavious-wpatty** [waviousllc/wav-build#3]
### Issue
There appears to be a race condition where `patch_image_header.py` attempts to remove before tmp.bin is created. 

~~~
Traceback (most recent call last):
  File "/usr/local/build/src/rtos/wav-build/cmake/../scripts/patch_image_header.py", line 100, in <module>
    main(args.elf, args.prefix)
  File "/usr/local/build/src/rtos/wav-build/cmake/../scripts/patch_image_header.py", line 75, in main
    os.remove("tmp.bin")
FileNotFoundError: [Errno 2] No such file or directory: 'tmp.bin'
~~~

**Comment by wavious-wpatty** [comment]
The issue was related to using tmp.bin filename for all targets. When using parallel builds (-j option), a race condition could occur where one target could delete another target's tmp.bin file. The script now produces a filename unique to each target.
